
/*------------------------------------------------------------------------
    File        : IGetDataTableResponse
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : hdaniels
    Created     : Thu Apr 18 21:20:12 EDT 2019
    Notes       : 
  ----------------------------------------------------------------------*/

using Ccs.BusinessLogic.IGetDataTableResponse from propath.
using Ccs.BusinessLogic.IGetTableResultCountResponse from propath.

interface Pmfo.Core.BusinessLogic.IGetDataTableResponse inherits IGetTableResultCountResponse:        
end interface.